config/routes.rb
Rails.application.routes.draw do
  resources :leagues
  resources :rules

  shallow do
    resources :tournaments do
      resources :divisions
      resources :rounds do
        resources :matches do
          resources :lineups
        end
      end
    end
  end

 
  resources :players do
    resources :games
  end
  shallow do
    resources :teams do
      member do
        delete 'remove_captain' => :remove_captain
        post 'make_captain' => :make_captain
      end
      resources :players
      get 'join_tournaments' => :join_tournaments
      patch 'join_divisions' => :join_divisions
      patch 'add_player' => :add_player
    end
  end
  get 'games' => 'games#index'

  get 'search' => 'search#index'
  devise_for :users, skip: :registrations,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks'
    }
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: {
        new: 'sign_up',
        sign_in: 'login',
        sign_out: 'logout',
      },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  post '/users/delete_identity' => 'users#delete_identity'

  match '/users/:id/finish_signup' => 'users#finish_signup',
    via: [:get, :patch], :as => :finish_signup

  match '/users/link_player' => 'users#link_player',
    via: [:post], :as => :link_player

  get 'dashboard' => 'dashboard#index'

  root 'dashboard#index'
  resources :messages
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if user_signed_in? and current_user.player
      @teams = current_user.player.teams.paginate(page: params[:page], per_page: 15)
      @open_tournaments = current_user.player.open_tournaments.paginate(page: params[:otpage], per_page: 15)
      @past_tournaments = current_user.player.past_tournaments.paginate(page: params[:ptpage], per_page: 15)
    else
      @teams = [] # TODO all competing teams Team.all_competing
      @open_tournaments = Division.open_tournaments.paginate(page: params[:otpage], per_page: 15)
      @past_tournaments = Division.past_tournaments.paginate(page: params[:ptpage], per_page: 15)
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<%# TODO this section should be a case statement? %>
<% if not current_user %>
  <%# TODO if you're not a user, what can you see? %>
  <h1>It's more fun if you're a user. Consider <%= link_to 'signing in', new_user_session_path %></h1>
<% elsif current_user.player.nil? %>
  <h1>Tournaments</h1>
  <%# TODO make to partial %>
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>League</th>
      <th>Description</th>
      <th>Division</th>
    </tr>
  </thead>
  <tbody>
    <% @open_tournaments.each do |tournament| %>
      <tr>
        <td><%= link_to tournament.name, tournament %></td>
        <td><%= link_to tournament.league.name, tournament.league %></td>
        <td><%= tournament.description %></td>
        <td><%= tournament.player_divisions(current_user.player).name if current_user.player %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
  <%= will_paginate @open_tournaments, renderer: BootstrapPagination::Rails, param_name: :otpage %>
  
  <h1>Past Tournaments</h1>
  <%# TODO make to partial %>
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>League</th>
      <th>Description</th>
      <th>Division</th>
    </tr>
  </thead>
  <tbody>
    <% @past_tournaments.each do |tournament| %>
      <tr>
        <td><%= link_to tournament.name, tournament %></td>
        <td><%= link_to tournament.league.name, tournament.league %></td>
        <td><%= tournament.description %></td>
        <td><%= tournament.player_divisions(current_user.player).name if current_user.player %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
  <%= will_paginate @past_tournaments, renderer: BootstrapPagination::Rails, param_name: :ptpage %>

  <h2>You cannot join teams without a <%= link_to 'player', new_player_path %>.</h2>
<% elsif current_user.player.teams.size > 0 %>
  <div class="row">
    <h1>My <%= "Team".pluralize(@teams.size) %></h1>
    <% @teams.each do |t| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <%= image_tag t.image, alt: "#{t.name} image" unless t.image.blank? %>
          <div class="caption">
            <h3><%= link_to "#{t.name} Team", t %></h3>
            <p class='text-right'><strong>Captains:</strong></p>
            <% t.players.each do |p| %>
              <% if t.captains.include?(p) %>
                <div class="text-right">
                  <%= p.name %> <span class="glyphicon glyphicon-star" title="Team captain"></span>
                </div>
              <% end %>
            <% end %>
            <p class='text-right' title='<%= "#{t.players.size} player".pluralize(t.players.size) %>'><%= link_to "...", t %></p>
            <% if current_user.admin? or t.captains.include?(current_user.player) %>
              <hr />
              <div class="text-right">
                <%= button_to 'Add Players', t, class: 'btn btn-default', method: :get %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <%= will_paginate @teams, renderer: BootstrapPagination::Rails, param_name: :page %>
  </div>
  <div class='row'>
    <h1><%= "Tournament".pluralize(@open_tournaments.size) %></h1>
    <% @open_tournaments.each do |t| %>
      <div class="col-sm-6 col-md-6">
        <div class="thumbnail">
          <%= image_tag t.image, alt: "#{t.name} image" unless t.image.blank? %>
          <div class="caption">
            <h3><%= link_to "#{t.name}: #{t.player_divisions(current_user.player).name}", t %></h3>
            <div class="text-right">
              Next Match:
              <%# TODO display next match here %>
              Team Foo vs <%= t.player_team(current_user.player).name %>
              <hr />
              <div class="text-right">
                Line Up Here
                <%#= button_to 'Line Up', lineup_path(t), class: 'btn btn-default', method: :get %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= will_paginate @open_tournaments, renderer: BootstrapPagination::Rails, param_name: :otpage %>
  </div>

  <h1><%= "Past " + "Tournament".pluralize(@past_tournaments.size) %></h1>
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>League</th>
      <th>Description</th>
      <th>Division</th>
    </tr>
  </thead>
  <tbody>
    <% @past_tournaments.each do |tournament| %>
      <tr>
        <td><%= link_to tournament.name, tournament %></td>
        <td><%= link_to tournament.league.name, tournament.league %></td>
        <td><%= tournament.description %></td>
        <td><%= tournament.player_divisions(current_user.player).name if current_user.player %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
  <%= will_paginate @past_tournaments, renderer: BootstrapPagination::Rails, param_name: :ptpage %>
<% else %>
  <h1>You have not <%= link_to 'joined a team', teams_path %> yet.</h1>
<% end %>