config/routes.rb
Rails.application.routes.draw do
  resources :leagues
  resources :rules

  shallow do
    resources :tournaments do
      resources :divisions
      resources :rounds do
        resources :matches do
          resources :lineups
        end
      end
    end
  end

 
  resources :players do
    resources :games
  end
  shallow do
    resources :teams do
      member do
        delete 'remove_captain' => :remove_captain
        post 'make_captain' => :make_captain
      end
      resources :players
      get 'join_tournaments' => :join_tournaments
      patch 'join_divisions' => :join_divisions
      patch 'add_player' => :add_player
    end
  end
  get 'games' => 'games#index'

  get 'search' => 'search#index'
  devise_for :users, skip: :registrations,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks'
    }
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: {
        new: 'sign_up',
        sign_in: 'login',
        sign_out: 'logout',
      },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  post '/users/delete_identity' => 'users#delete_identity'

  match '/users/:id/finish_signup' => 'users#finish_signup',
    via: [:get, :patch], :as => :finish_signup

  match '/users/link_player' => 'users#link_player',
    via: [:post], :as => :link_player

  get 'dashboard' => 'dashboard#index'

  root 'dashboard#index'
  resources :messages
end

app/models/league.rb
class League < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name

  has_and_belongs_to_many :rules
  accepts_nested_attributes_for :rules #, reject_if: :new_record?, allow_destroy: true
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    if current_user.admin?
      @league = League.new
    else
      msg = { alert: "Only administrators can create or manipulate leagues. Contact site administrator #{CHESS_ADMIN_EMAIL}" }
      respond_to do |format|
        format.html { redirect_to root_path, msg }
        format.json { render json: "", status: :unprocessable_entity }
      end
    end
  end

  # GET /leagues/1/edit
  def edit
    unless current_user.admin?
      respond_to do |format|
        format.html { redirect_to root_url, alert: "You are not a site admin. Contact #{CHESS_ADMIN_EMAIL}." }
        format.json { render json: "", status: :unprocessable_entity }
      end
      return
    end
  end

  # POST /leagues
  # POST /leagues.json
  def create
    if current_user.admin?
      @league = League.new(league_params)

      respond_to do |format|
        if @league.save
          format.html { redirect_to @league, notice: 'League was successfully created.' }
          format.json { render :show, status: :created, location: @league }
        else
          format.html { render :new }
          format.json { render json: @league.errors, status: :unprocessable_entity }
        end
      end
    else
      msg = { alert: "Only administrators can create or manipulate leagues. Contact site administrator #{CHESS_ADMIN_EMAIL}" }
      respond_to do |format|
        format.html { redirect_to root_path, msg }
        format.json { render json: "", status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    if current_user.admin?
      respond_to do |format|
        if @league.update(league_params)
          format.html { redirect_to @league, notice: 'League was successfully updated.' }
          format.json { render :show, status: :ok, location: @league }
        else
          format.html { render :edit }
          format.json { render json: @league.errors, status: :unprocessable_entity }
        end
      end
    else
      msg = { alert: "Only administrators can create or manipulate leagues. Contact site administrator #{CHESS_ADMIN_EMAIL}" }
      respond_to do |format|
        format.html { redirect_to root_path, msg }
        format.json { render json: "", status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    if current_user.admin?
      @league.destroy
      respond_to do |format|
        format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      msg = { alert: "Only administrators can create or manipulate leagues. Contact site administrator #{CHESS_ADMIN_EMAIL}" }
      respond_to do |format|
        format.html { redirect_to root_path, msg }
        format.json { render json: "", status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :image, :description, rule_ids: [])
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league, html: { class: 'form-horizontal' }) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'name *', class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.text_field :image, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= f.text_area :description, size: '20x10', class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rules, class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'> 
      <%= f.collection_check_boxes :rule_ids, Rule.all, :id, :name do |b| %>
        <%= b.label class:"control-label" do %>
          <%= b.check_box + b.text %>
        <% end %>
        <br />
      <% end %> 
      <%= link_to 'Add Rule', new_rule_path, class: 'btn btn-default' %>
    </div>
  </div>
  <div class="text-center">
    <%= f.submit 'Save', class: "btn btn-primary" %>
  </div>
  <div class='text-center'>
    <small>* Required</small>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form' %>

app/views/leagues/index.html.erb
<h1>Listing Leagues</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr data-no-turbolink>
        <td><%= link_to league.name, league %></td>
        <td><%= league.description %></td>
        <td><%= link_to 'Edit', edit_league_path(league), class: 'form-control btn btn-default' if current_user.admin?  %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' }, class: 'form-control btn btn-default' if current_user.admin? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />
<div class='row'>
  <div class='col-sm-4'>
    <%= button_to 'New League', new_league_path, class: "form-control btn btn-primary", method: :get %>
  </div>
</div>

app/views/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form' %>

app/views/leagues/show.html.erb
<div class='row'>
  <div class='col-sm-10'>
    <h2><%= @league.name %> league</h2>
  </div>
</div>

<div class='row'>
  <div class='col-sm-10'>
    <%= image_tag @league.image, alt: @league.name unless @league.image.blank? %>
  </div>
</div>

<div class='row'>
  <div class='col-sm-10'>
    <%= @league.description %>
  </div>
</div>

<div class='row'>
  <div class='col-sm-10'>
    <h3>Rules</h3>
    <ul>
<% @league.rules.each do |rule| %>
      <li><%= link_to rule.name, rule %></li>
<% end %>
    </ul>
  </div>
</div>

<hr />
<div class='row'>
  <div class='col-sm-3'>
    <%= button_to 'Leagues', leagues_path, method: :get, class: 'form-control btn btn-default', title: 'List all tournaments' %>
  </div>
  <div class='col-sm-2'>
    <%= button_to 'Edit', edit_league_path(@league), method: :get, class: 'form-control btn btn-primary' %>
  </div>
</div>