config/routes.rb
Rails.application.routes.draw do
  resources :leagues
  resources :rules

  shallow do
    resources :tournaments do
      resources :divisions
      resources :rounds do
        resources :matches do
          resources :lineups
        end
      end
    end
  end

 
  resources :players do
    resources :games
  end
  shallow do
    resources :teams do
      member do
        delete 'remove_captain' => :remove_captain
        post 'make_captain' => :make_captain
      end
      resources :players
      get 'join_tournaments' => :join_tournaments
      patch 'join_divisions' => :join_divisions
      patch 'add_player' => :add_player
    end
  end
  get 'games' => 'games#index'

  get 'search' => 'search#index'
  devise_for :users, skip: :registrations,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks'
    }
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: {
        new: 'sign_up',
        sign_in: 'login',
        sign_out: 'logout',
      },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  post '/users/delete_identity' => 'users#delete_identity'

  match '/users/:id/finish_signup' => 'users#finish_signup',
    via: [:get, :patch], :as => :finish_signup

  match '/users/link_player' => 'users#link_player',
    via: [:post], :as => :link_player

  get 'dashboard' => 'dashboard#index'

  root 'dashboard#index'
  resources :messages
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :divisions
  has_many :rounds
  belongs_to :league

  accepts_nested_attributes_for :rounds, allow_destroy: true
  accepts_nested_attributes_for :divisions, allow_destroy: true

  validates_presence_of :name
  validates_uniqueness_of :name

  validates_presence_of :boards_per_match
  validates :boards_per_match, inclusion: { in: (1..100).to_a,
    message: "%{value} is not a valid size" }

  def teams
    Team.joins(:divisions => :tournament).where('tournaments.id = ?',id).group(:id)
  end

  def players
    Player.joins(:teams => :divisions).where('tournament_id = ?', id)
  end

  # returns division for this tournament and player
  # note that a user can only be competing with 1 team in 1 division of every tournament
  def player_divisions(player)
    Division.joins(:teams => :players).where('tournament_id = ? AND players.id = ?', id, player.id).uniq.last
  end

  # returns team for this tournament and player
  # note that a user can only be competing with 1 team in 1 division of every tournament
  def player_team(player)
    Team.joins(:players).where( 'players_teams.player_id = ?', player.id ).uniq.last
  end

  def self.open_tournaments
    today = Time.now
    where('end_date >= ?', today).group(:id)
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.paginate(page: params[:page], per_page: 15)
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    if current_user.admin?
      @tournament = Tournament.new
    else
      msg = { alert: "Only administrators can create or manipulate tournaments. Contact site administrator #{CHESS_ADMIN_EMAIL}" }
      respond_to do |format|
        format.html { redirect_to root_path, msg }
        format.json { render json: "", status: :unprocessable_entity }
      end
    end
  end

  # GET /tournaments/1/edit
  def edit
    pri_user = current_user.admin?
    unless pri_user
      respond_to do |format|
        format.html { redirect_to root_url, alert: "You are not a site admin. Contact #{CHESS_ADMIN_EMAIL}." }
        format.json { render json: "", status: :unprocessable_entity }
      end
      return
    end
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    if current_user.admin?
      @tournament = Tournament.new(tournament_params)

      respond_to do |format|
        if @tournament.save
          if @tournament.divisions.size < 1
            begin
              logger.info "#{self.class}.#{__method__} Adding default division"
              @tournament.divisions.create name: "A"
              @tournament.save
              logger.info "#{self.class}.#{__method__} done Adding default division"
            rescue => e
              logger.error "#{self.class}.#{__method__} #{e.class} #{e.message} #{e.backtrace.join(', ')}"
            end
          end
          format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
          format.json { render :show, status: :created, location: @tournament }
        else
          format.html { render :new }
          format.json { render json: @tournament.errors, status: :unprocessable_entity }
        end
      end
    else
      msg = { alert: "Only administrators can create or manipulate tournaments. Contact site administrator #{CHESS_ADMIN_EMAIL}" }
      respond_to do |format|
        format.html { redirect_to root_path, msg }
        format.json { render json: "", status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    if current_user.admin?
      respond_to do |format|
        begin
          if @tournament.update(tournament_params)
            format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
            format.json { render :show, status: :ok, location: @tournament }
          else
            format.html { render :edit }
            format.json { render json: @tournament.errors, status: :unprocessable_entity }
          end
        rescue ActiveRecord::RecordNotDestroyed => e
          flash[:alert] = "Failed to delete record. Make sure round does not have any matches."
          format.html { render :edit }
          format.json { render json: @tournament.errors, status: :unprocessable_entity }
        end
      end
    else
      msg = { alert: "Only administrators can create or manipulate tournaments. Contact site administrator #{CHESS_ADMIN_EMAIL}" }
      respond_to do |format|
        format.html { redirect_to tournament_url(@tournament), msg }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    if current_user.admin?
      @tournament.destroy
      respond_to do |format|
        format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      msg = { alert: "Only administrators can create or manipulate tournaments. Contact site administrator #{CHESS_ADMIN_EMAIL}" }
      respond_to do |format|
        format.html { redirect_to root_path, msg }
        format.json { render json: "", status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :image, :description, :league_id, :start_date, :end_date, :boards_per_match, division_ids: [], rounds_attributes: [ :name, :description, :start_date, :end_date, :_destroy, :id ])
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
  def collection_links(c)
    c.collect do |r|
      link_to r.name, r
    end.join(', ')
  end
end

app/views/tournaments/_form.html.erb
<%= form_for(@tournament, html: { class: 'form-horizontal' }) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :leagues, class: 'control-label col-sm-2' %>
    <div class='col-sm-10'>
      <%= f.collection_radio_buttons :league_id, League.all, :id,
        :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label 'name *', class: 'control-label col-sm-2' %>
    <div class='col-sm-10'>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, class: 'control-label col-sm-2' %>
    <div class='col-sm-10'>
      <%= f.text_field :image, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label col-sm-2' %>
    <div class='col-sm-10'>
      <%= f.text_area :description, size: '20x10', class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :divisions, class: 'control-label col-sm-2' %>
    <div class='col-sm-2'>
      <%= f.collection_check_boxes :division_ids, @tournament.divisions, :id,
        :name do |b| %>
        <%= b.label class:"control-label" do %>
          <%= b.check_box + b.text %>
        <% end %>
        <br />
      <% end %> 
      <% unless params[:action] == 'new' %>
      <%= link_to 'Add Division', new_tournament_division_path(@tournament), class: 'btn btn-default' %>
      <% end %>
    </div>
    <%= f.label :rounds, class: 'control-label col-sm-2' %>
    <div class='text-right col-sm-6'>
      <fieldset>
        <%= f.fields_for :rounds do |builder| %>
          <%= render 'rounds/round_fields', f: builder %>
        <% end %>
        <hr />
        <% unless params[:action] == 'new' %>
          <%= link_to_add_fields "Add Round", f, :rounds %>
        <% end %>
      </fieldset>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_date, class: 'control-label col-sm-2' %>
    <div class='col-sm-10'>
      <%= f.datetime_select :start_date, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_date, class: 'control-label col-sm-2' %>
    <div class='col-sm-10'>
      <%= f.datetime_select :end_date, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :boards_per_match, class: 'control-label col-sm-2' %>
    <div class='col-sm-10'>
      <%= f.select :boards_per_match, (1..100).to_a, class: 'form-control' %>
    </div>
  </div>
  <div class="text-center">
    <div class="form-group">
    <%= link_to 'Cancel', @tournament, class: 'btn btn-default' %>
    <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="text-center">
    <small>* Required</small>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>
<%= render 'form' %>

app/views/tournaments/index.html.erb
<h1>Listing Tournaments</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>League</th>
      <th>Image</th>
      <th>Description</th>
      <th>Divisions</th>
      <th>Rounds</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= link_to tournament.name, tournament %></td>
        <td><%= tournament.league.name %></td>
        <td><%= image_tag tournament.image unless tournament.image.blank? %></td>
        <td><%= tournament.description %></td>
        <%# TODO should show if team belongs to this tournament.division %>
        <td><%= collection_links(tournament.divisions).html_safe %></td>
        <td><%= collection_links(tournament.rounds).html_safe %></td>
        <td><%= link_to 'New Division', new_tournament_division_path(tournament), class: 'form-control btn btn-default' if current_user.admin? %></td>
        <td><%= link_to 'New Round', new_tournament_round_path(tournament), class: 'form-control btn btn-default' if current_user.admin? %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament), class: 'form-control btn btn-default' if current_user.admin? %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' }, class: 'form-control btn btn-default' if current_user.admin? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class='row'>
  <div class='col-sm-4'>
    <%= button_to 'New Tournament', new_tournament_path, class: "form-control btn btn-primary", method: :get %>
  </div>
</div>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>
<%= render 'form' %>

app/views/tournaments/show.html.erb
<div class='row'>
  <div class='col-sm-10'>
    <h2><%= @tournament.name %></h2>
    <% if current_user.admin? %>
    <p><%= button_to 'Edit', edit_tournament_path(@tournament), method: :get, class: 'btn btn-primary' %></p>
    <% end %>
    <h4><%= link_to "#{@tournament.league.name} league", @tournament.league %></h4>
      <strong>Rules</strong>
      <ul>
      <% @tournament.league.rules.each do |rule| %>
        <li><%= link_to rule.name, rule %></li>
      <% end %>
      </ul>
  </div>
</div>
<div class='row'>
  <div class='col-sm-10'>
    <%= image_tag @tournament.image, alt: @tournament.name unless @tournament.image.blank? %>
  </div>
</div>
<div class='row'>
  <div class='col-sm-10'>
    <%= @tournament.description %>
  </div>
</div>
<br />
<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#rounds" aria-controls="rounds" role="tab" data-toggle="tab">Rounds</a>
    </li>
    <li role="presentation">
      <a href="#divisions" aria-controls="divisions" role="tab" data-toggle="tab">Divisions</a>
    </li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="rounds">
      <h1>Rounds</h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Matches</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tournament.rounds.each do |round| %>
            <tr>
              <td><%= link_to round.name, round %></td>
              <td><span title="Start time: <%= round.start_date %>. End time: <%= round.end_date %>"><%= round.start_date %> (<%= distance_of_time_in_words round.end_date, round.start_date %>)</span></td>
              <td>
                <table class='table table-striped'>
                  <thead><tr><th>Home</th><th></th><th>Guest</th><th></th></tr></thead>
                  <tbody>
                    <% round.matches.each do |match| %>
                      <tr>
                        <td><%= match.home_team.name if match.home_team.respond_to?(:name) %></td>
                        <td>vs</td>
                        <td><%= match.guest_team.name if match.guest_team.respond_to?(:name) %></td>
                        <td><% if current_user.admin? %><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %><% end %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </td>
              <td>
                <div class='btn-group' role='group' aria-label='tournaments control'>
                  <% if current_user.admin? %>
                  <%= link_to 'Edit Round', edit_round_path(round), method: :get, class: 'btn btn-default' %>
                  <%= link_to 'Add Match', new_round_match_path(round_id: round), method: :get, class: 'btn btn-success' %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div role="tabpanel" class="tab-pane" id="divisions">
      <h1>Divisions</h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Teams</th>
          </tr>
        </thead>

        <tbody>
      <% @tournament.divisions.each do |division| %>
        <tr>
          <td>
            <h3><%= link_to division.name, division, title: division.description  %></h3>
          </td>
          <td>
            <ul style='list-style-type: none;'>
              <% division.teams.each do |team| %>
                <li><%= link_to team.name, team %></li>
              <% end %>
            </ul>
          </td>
        </tr>
      <% end %>
        </tbody>
      </table>
    </div>
</div>